System.Net.WebException: An error occurred while sending the request.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: Удаленный хост принудительно разорвал существующее подключение..
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at HtmlAgilityPack.HtmlWeb.Get(Uri uri, String method, String path, HtmlDocument doc, IWebProxy proxy, ICredentials creds)
   at HtmlAgilityPack.HtmlWeb.Load(Uri uri, String method)
   at cardscore_api.Services.Soccer365ParserService.ParsePageActive(String url, String h1Element) in C:\Users\komko\OneDrive\Документы\Work\cardscore\cardscore-api\Services\ParserServices\Soccer365ParserService.cs:line 246
   at cardscore_api.Services.Soccer365ParserService.GetActiveGamesByUrl(String url, String name) in C:\Users\komko\OneDrive\Документы\Work\cardscore\cardscore-api\Services\ParserServices\Soccer365ParserService.cs:line 134
   at cardscore_api.Services.NotificationWorkerService.GetActiveGames(String url, String name) in C:\Users\komko\OneDrive\Документы\Work\cardscore\cardscore-api\Services\NotificationWorkerService.cs:line 268
   at cardscore_api.Services.NotificationWorkerService.GetDataByNotificator(UserNotificationOption notificator) in C:\Users\komko\OneDrive\Документы\Work\cardscore\cardscore-api\Services\NotificationWorkerService.cs:line 240
   at cardscore_api.Services.NotificationWorkerService.<>c__DisplayClass5_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\komko\OneDrive\Документы\Work\cardscore\cardscore-api\Services\NotificationWorkerService.cs:line 50
